# Generated by Django 5.2.4 on 2025-08-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0002_purchase_payment_method_purchase_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='composition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='medicine',
            name='indications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_generic',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ModelSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('substitution', 'Substitution'), ('disease', 'Disease')], max_length=20)),
                ('input_text', models.TextField(blank=True, default='')),
                ('results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_app.customer')),
                ('selected_medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_app.medicine')),
            ],
        ),
    ]
