# Generated by Django 5.2.4 on 2025-08-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0004_diseaserecommendation_substitutionrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsearchhistory',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='modelsearchhistory',
            name='selected_medicine',
        ),
        migrations.RemoveField(
            model_name='substitutionrecommendation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='substitutionrecommendation',
            name='recommended_medicine',
        ),
        migrations.RemoveField(
            model_name='substitutionrecommendation',
            name='source_medicine',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='indications',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='is_generic',
        ),
        migrations.DeleteModel(
            name='DiseaseRecommendation',
        ),
        migrations.DeleteModel(
            name='ModelSearchHistory',
        ),
        migrations.DeleteModel(
            name='SubstitutionRecommendation',
        ),
    ]
